# Generated by Django 3.2.23 on 2023-11-03 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='news',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.tag'),
        ),
    ]
