# Generated by Django 3.2.23 on 2023-11-03 17:57

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 17, 56, 2, 322596)),
        ),
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
